[package]
name = "tp-3-and-4"
version = "0.1.0"
authors = ["Mikkel ALMONTE--RINGAUD"]
description = "Module contenant ma résolution du TP 3 et 4."
edition = "2021"

[dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
inquire = "0.7.5"
sha1 = "0.10.6"
sha2 = "0.10.8"
